### ISSUE TITLE
Editing Terraform files causes a huge chain of plugin processes to start/kill - "GRPCProvider: GetSchema"

### ISSUE THREAD

**Issue by davidjoliver86** [juliosueiras/terraform-lsp#47] opened 2020-01-01 02:52 UTC
When I load VSCode, I'm able to have one interaction with the language server plugin (e.g. hitting alt+space for resource autocompletion). Then after that one interaction, there seems to be a huge spike in CPU/IO usage lasting almost a minute where the plugin doesn't respond and only shows "Loading...".

Upon looking at the language server output, it seems like lots of `terraform-provider-aws` processes are repeatedly starting and killing. Here's some of the log output - and note that this only encompasses about _two seconds_ of time:

The processes seem to get killed off right after `[TRACE] GRPCProvider: GetSchema`.
```
2019/12/31 18:43:30 Server started
2019/12/31 18:43:39 [DEBUG] plugin dirs: []string{".", "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin", "terraform.d/plugins/linux_amd64", "/home/davido/<REDACTED>/.terraform/plugins/linux_amd64", "/home/davido/.terraform.d/plugins", "/home/davido/.terraform.d/plugins/linux_amd64", "/home/davido/go/bin"}
2019/12/31 18:43:39 [DEBUG] checking for provider in "."
2019/12/31 18:43:39 [DEBUG] checking for provider in "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-alicloud_v1.67.0_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-archive_v1.3.0_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-aws_v2.43.0_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-azurerm_v1.39.0_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-external_v1.2.0_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-google_v3.3.0_x5"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-helm_v0.10.4_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-kubernetes_v1.10.0_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-null_v2.1.2_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-random_v2.2.1_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-template_v2.1.2_x4"
2019-12-31T18:43:39.528-0800 [INFO]  plugin: configuring client automatic mTLS
2019-12-31T18:43:39.587-0800 [DEBUG] plugin: starting plugin: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 args=[/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4]
2019-12-31T18:43:39.587-0800 [DEBUG] plugin: plugin started: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6862
2019-12-31T18:43:39.588-0800 [DEBUG] plugin: waiting for RPC address: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4
2019-12-31T18:43:39.639-0800 [INFO]  plugin.terraform-provider-aws_v2.43.0_x4: configuring server automatic mTLS: timestamp=2019-12-31T18:43:39.638-0800
2019-12-31T18:43:39.708-0800 [DEBUG] plugin: using plugin: version=5
2019-12-31T18:43:39.708-0800 [DEBUG] plugin.terraform-provider-aws_v2.43.0_x4: plugin address: network=unix address=/tmp/plugin648467804 timestamp=2019-12-31T18:43:39.706-0800
2019/12/31 18:43:39 [TRACE] GRPCProvider: GetSchema
2019-12-31T18:43:39.845-0800 [DEBUG] plugin: plugin process exited: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6862
2019-12-31T18:43:39.845-0800 [DEBUG] plugin: plugin exited
2019/12/31 18:43:39 [DEBUG] plugin dirs: []string{".", "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin", "terraform.d/plugins/linux_amd64", "/home/davido/<REDACTED>/.terraform/plugins/linux_amd64", "/home/davido/.terraform.d/plugins", "/home/davido/.terraform.d/plugins/linux_amd64", "/home/davido/go/bin"}
2019/12/31 18:43:39 [DEBUG] checking for provider in "."
2019/12/31 18:43:39 [DEBUG] checking for provider in "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-alicloud_v1.67.0_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-archive_v1.3.0_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-aws_v2.43.0_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-azurerm_v1.39.0_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-external_v1.2.0_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-google_v3.3.0_x5"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-helm_v0.10.4_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-kubernetes_v1.10.0_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-null_v2.1.2_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-random_v2.2.1_x4"
2019/12/31 18:43:39 [DEBUG] found provider "terraform-provider-template_v2.1.2_x4"
2019-12-31T18:43:39.846-0800 [INFO]  plugin: configuring client automatic mTLS
2019-12-31T18:43:39.883-0800 [DEBUG] plugin: starting plugin: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 args=[/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4]
2019-12-31T18:43:39.883-0800 [DEBUG] plugin: plugin started: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6886
2019-12-31T18:43:39.883-0800 [DEBUG] plugin: waiting for RPC address: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4
2019-12-31T18:43:39.901-0800 [INFO]  plugin.terraform-provider-aws_v2.43.0_x4: configuring server automatic mTLS: timestamp=2019-12-31T18:43:39.901-0800
2019-12-31T18:43:39.936-0800 [DEBUG] plugin.terraform-provider-aws_v2.43.0_x4: plugin address: network=unix address=/tmp/plugin435468965 timestamp=2019-12-31T18:43:39.936-0800
2019-12-31T18:43:39.936-0800 [DEBUG] plugin: using plugin: version=5
2019/12/31 18:43:39 [TRACE] GRPCProvider: GetSchema
2019-12-31T18:43:40.067-0800 [DEBUG] plugin: plugin process exited: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6886
2019-12-31T18:43:40.067-0800 [DEBUG] plugin: plugin exited
2019/12/31 18:43:40 [DEBUG] plugin dirs: []string{".", "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin", "terraform.d/plugins/linux_amd64", "/home/davido/<REDACTED>/.terraform/plugins/linux_amd64", "/home/davido/.terraform.d/plugins", "/home/davido/.terraform.d/plugins/linux_amd64", "/home/davido/go/bin"}
2019/12/31 18:43:40 [DEBUG] checking for provider in "."
2019/12/31 18:43:40 [DEBUG] checking for provider in "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-alicloud_v1.67.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-archive_v1.3.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-aws_v2.43.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-azurerm_v1.39.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-external_v1.2.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-google_v3.3.0_x5"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-helm_v0.10.4_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-kubernetes_v1.10.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-null_v2.1.2_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-random_v2.2.1_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-template_v2.1.2_x4"
2019-12-31T18:43:40.068-0800 [INFO]  plugin: configuring client automatic mTLS
2019-12-31T18:43:40.105-0800 [DEBUG] plugin: starting plugin: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 args=[/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4]
2019-12-31T18:43:40.107-0800 [DEBUG] plugin: plugin started: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6900
2019-12-31T18:43:40.107-0800 [DEBUG] plugin: waiting for RPC address: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4
2019-12-31T18:43:40.128-0800 [INFO]  plugin.terraform-provider-aws_v2.43.0_x4: configuring server automatic mTLS: timestamp=2019-12-31T18:43:40.128-0800
2019-12-31T18:43:40.162-0800 [DEBUG] plugin.terraform-provider-aws_v2.43.0_x4: plugin address: address=/tmp/plugin085606913 network=unix timestamp=2019-12-31T18:43:40.162-0800
2019-12-31T18:43:40.162-0800 [DEBUG] plugin: using plugin: version=5
2019/12/31 18:43:40 [TRACE] GRPCProvider: GetSchema
2019-12-31T18:43:40.280-0800 [DEBUG] plugin: plugin process exited: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6900
2019-12-31T18:43:40.280-0800 [DEBUG] plugin: plugin exited
2019/12/31 18:43:40 [DEBUG] plugin dirs: []string{".", "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin", "terraform.d/plugins/linux_amd64", "/home/davido/<REDACTED>/.terraform/plugins/linux_amd64", "/home/davido/.terraform.d/plugins", "/home/davido/.terraform.d/plugins/linux_amd64", "/home/davido/go/bin"}
2019/12/31 18:43:40 [DEBUG] checking for provider in "."
2019/12/31 18:43:40 [DEBUG] checking for provider in "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-alicloud_v1.67.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-archive_v1.3.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-aws_v2.43.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-azurerm_v1.39.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-external_v1.2.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-google_v3.3.0_x5"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-helm_v0.10.4_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-kubernetes_v1.10.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-null_v2.1.2_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-random_v2.2.1_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-template_v2.1.2_x4"
2019-12-31T18:43:40.281-0800 [INFO]  plugin: configuring client automatic mTLS
2019-12-31T18:43:40.314-0800 [DEBUG] plugin: starting plugin: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 args=[/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4]
2019-12-31T18:43:40.314-0800 [DEBUG] plugin: plugin started: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6913
2019-12-31T18:43:40.314-0800 [DEBUG] plugin: waiting for RPC address: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4
2019-12-31T18:43:40.333-0800 [INFO]  plugin.terraform-provider-aws_v2.43.0_x4: configuring server automatic mTLS: timestamp=2019-12-31T18:43:40.333-0800
2019-12-31T18:43:40.369-0800 [DEBUG] plugin: using plugin: version=5
2019-12-31T18:43:40.369-0800 [DEBUG] plugin.terraform-provider-aws_v2.43.0_x4: plugin address: address=/tmp/plugin156006182 network=unix timestamp=2019-12-31T18:43:40.369-0800
2019/12/31 18:43:40 [TRACE] GRPCProvider: GetSchema
2019-12-31T18:43:40.491-0800 [DEBUG] plugin: plugin process exited: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6913
2019-12-31T18:43:40.491-0800 [DEBUG] plugin: plugin exited
2019/12/31 18:43:40 [DEBUG] plugin dirs: []string{".", "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin", "terraform.d/plugins/linux_amd64", "/home/davido/<REDACTED>/.terraform/plugins/linux_amd64", "/home/davido/.terraform.d/plugins", "/home/davido/.terraform.d/plugins/linux_amd64", "/home/davido/go/bin"}
2019/12/31 18:43:40 [DEBUG] checking for provider in "."
2019/12/31 18:43:40 [DEBUG] checking for provider in "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-alicloud_v1.67.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-archive_v1.3.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-aws_v2.43.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-azurerm_v1.39.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-external_v1.2.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-google_v3.3.0_x5"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-helm_v0.10.4_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-kubernetes_v1.10.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-null_v2.1.2_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-random_v2.2.1_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-template_v2.1.2_x4"
2019-12-31T18:43:40.492-0800 [INFO]  plugin: configuring client automatic mTLS
2019-12-31T18:43:40.524-0800 [DEBUG] plugin: starting plugin: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 args=[/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4]
2019-12-31T18:43:40.524-0800 [DEBUG] plugin: plugin started: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6926
2019-12-31T18:43:40.524-0800 [DEBUG] plugin: waiting for RPC address: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4
2019-12-31T18:43:40.542-0800 [INFO]  plugin.terraform-provider-aws_v2.43.0_x4: configuring server automatic mTLS: timestamp=2019-12-31T18:43:40.542-0800
2019-12-31T18:43:40.575-0800 [DEBUG] plugin.terraform-provider-aws_v2.43.0_x4: plugin address: address=/tmp/plugin636624704 network=unix timestamp=2019-12-31T18:43:40.575-0800
2019-12-31T18:43:40.575-0800 [DEBUG] plugin: using plugin: version=5
2019/12/31 18:43:40 [TRACE] GRPCProvider: GetSchema
2019-12-31T18:43:40.698-0800 [DEBUG] plugin: plugin process exited: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6926
2019-12-31T18:43:40.698-0800 [DEBUG] plugin: plugin exited
2019/12/31 18:43:40 [DEBUG] plugin dirs: []string{".", "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin", "terraform.d/plugins/linux_amd64", "/home/davido/<REDACTED>/.terraform/plugins/linux_amd64", "/home/davido/.terraform.d/plugins", "/home/davido/.terraform.d/plugins/linux_amd64", "/home/davido/go/bin"}
2019/12/31 18:43:40 [DEBUG] checking for provider in "."
2019/12/31 18:43:40 [DEBUG] checking for provider in "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-alicloud_v1.67.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-archive_v1.3.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-aws_v2.43.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-azurerm_v1.39.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-external_v1.2.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-google_v3.3.0_x5"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-helm_v0.10.4_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-kubernetes_v1.10.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-null_v2.1.2_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-random_v2.2.1_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-template_v2.1.2_x4"
2019-12-31T18:43:40.699-0800 [INFO]  plugin: configuring client automatic mTLS
2019-12-31T18:43:40.735-0800 [DEBUG] plugin: starting plugin: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 args=[/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4]
2019-12-31T18:43:40.736-0800 [DEBUG] plugin: plugin started: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6938
2019-12-31T18:43:40.736-0800 [DEBUG] plugin: waiting for RPC address: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4
2019-12-31T18:43:40.754-0800 [INFO]  plugin.terraform-provider-aws_v2.43.0_x4: configuring server automatic mTLS: timestamp=2019-12-31T18:43:40.753-0800
2019-12-31T18:43:40.787-0800 [DEBUG] plugin.terraform-provider-aws_v2.43.0_x4: plugin address: address=/tmp/plugin714374408 network=unix timestamp=2019-12-31T18:43:40.787-0800
2019-12-31T18:43:40.787-0800 [DEBUG] plugin: using plugin: version=5
2019/12/31 18:43:40 [TRACE] GRPCProvider: GetSchema
2019-12-31T18:43:40.918-0800 [DEBUG] plugin: plugin process exited: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6938
2019-12-31T18:43:40.918-0800 [DEBUG] plugin: plugin exited
2019/12/31 18:43:40 [DEBUG] plugin dirs: []string{".", "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin", "terraform.d/plugins/linux_amd64", "/home/davido/<REDACTED>/.terraform/plugins/linux_amd64", "/home/davido/.terraform.d/plugins", "/home/davido/.terraform.d/plugins/linux_amd64", "/home/davido/go/bin"}
2019/12/31 18:43:40 [DEBUG] checking for provider in "."
2019/12/31 18:43:40 [DEBUG] checking for provider in "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-alicloud_v1.67.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-archive_v1.3.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-aws_v2.43.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-azurerm_v1.39.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-external_v1.2.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-google_v3.3.0_x5"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-helm_v0.10.4_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-kubernetes_v1.10.0_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-null_v2.1.2_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-random_v2.2.1_x4"
2019/12/31 18:43:40 [DEBUG] found provider "terraform-provider-template_v2.1.2_x4"
2019-12-31T18:43:40.918-0800 [INFO]  plugin: configuring client automatic mTLS
2019-12-31T18:43:40.954-0800 [DEBUG] plugin: starting plugin: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 args=[/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4]
2019-12-31T18:43:40.955-0800 [DEBUG] plugin: plugin started: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6951
2019-12-31T18:43:40.955-0800 [DEBUG] plugin: waiting for RPC address: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4
2019-12-31T18:43:40.972-0800 [INFO]  plugin.terraform-provider-aws_v2.43.0_x4: configuring server automatic mTLS: timestamp=2019-12-31T18:43:40.972-0800
2019-12-31T18:43:41.006-0800 [DEBUG] plugin: using plugin: version=5
2019-12-31T18:43:41.006-0800 [DEBUG] plugin.terraform-provider-aws_v2.43.0_x4: plugin address: address=/tmp/plugin411754137 network=unix timestamp=2019-12-31T18:43:41.006-0800
2019/12/31 18:43:41 [TRACE] GRPCProvider: GetSchema
2019-12-31T18:43:41.124-0800 [DEBUG] plugin: plugin process exited: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6951
2019-12-31T18:43:41.124-0800 [DEBUG] plugin: plugin exited
2019/12/31 18:43:41 [DEBUG] plugin dirs: []string{".", "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin", "terraform.d/plugins/linux_amd64", "/home/davido/<REDACTED>/.terraform/plugins/linux_amd64", "/home/davido/.terraform.d/plugins", "/home/davido/.terraform.d/plugins/linux_amd64", "/home/davido/go/bin"}
2019/12/31 18:43:41 [DEBUG] checking for provider in "."
2019/12/31 18:43:41 [DEBUG] checking for provider in "/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin"
2019/12/31 18:43:41 [DEBUG] found provider "terraform-provider-alicloud_v1.67.0_x4"
2019/12/31 18:43:41 [DEBUG] found provider "terraform-provider-archive_v1.3.0_x4"
2019/12/31 18:43:41 [DEBUG] found provider "terraform-provider-aws_v2.43.0_x4"
2019/12/31 18:43:41 [DEBUG] found provider "terraform-provider-azurerm_v1.39.0_x4"
2019/12/31 18:43:41 [DEBUG] found provider "terraform-provider-external_v1.2.0_x4"
2019/12/31 18:43:41 [DEBUG] found provider "terraform-provider-google_v3.3.0_x5"
2019/12/31 18:43:41 [DEBUG] found provider "terraform-provider-helm_v0.10.4_x4"
2019/12/31 18:43:41 [DEBUG] found provider "terraform-provider-kubernetes_v1.10.0_x4"
2019/12/31 18:43:41 [DEBUG] found provider "terraform-provider-null_v2.1.2_x4"
2019/12/31 18:43:41 [DEBUG] found provider "terraform-provider-random_v2.2.1_x4"
2019/12/31 18:43:41 [DEBUG] found provider "terraform-provider-template_v2.1.2_x4"
2019-12-31T18:43:41.124-0800 [INFO]  plugin: configuring client automatic mTLS
2019-12-31T18:43:41.158-0800 [DEBUG] plugin: starting plugin: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 args=[/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4]
2019-12-31T18:43:41.159-0800 [DEBUG] plugin: plugin started: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6964
2019-12-31T18:43:41.159-0800 [DEBUG] plugin: waiting for RPC address: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4
2019-12-31T18:43:41.176-0800 [INFO]  plugin.terraform-provider-aws_v2.43.0_x4: configuring server automatic mTLS: timestamp=2019-12-31T18:43:41.176-0800
2019-12-31T18:43:41.214-0800 [DEBUG] plugin.terraform-provider-aws_v2.43.0_x4: plugin address: address=/tmp/plugin099823748 network=unix timestamp=2019-12-31T18:43:41.214-0800
2019-12-31T18:43:41.214-0800 [DEBUG] plugin: using plugin: version=5
2019/12/31 18:43:41 [TRACE] GRPCProvider: GetSchema
2019-12-31T18:43:41.354-0800 [DEBUG] plugin: plugin process exited: path=/home/davido/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.43.0_x4 pid=6964
2019-12-31T18:43:41.354-0800 [DEBUG] plugin: plugin exited
```

**Comment by aliusmiles** [comment] 2020-01-03 18:43
Confirmed, lsp does  start/stop on each edit action instead of start once and wait for connections.  Doesn't freeze at "Loading..." for me though.

**Comment by beerygaz** [comment] 2020-01-07 12:11
I can confirm the same behavior on Windows.  VS Code 1.41.1

**Comment by hugbubby** [comment] 2020-02-06 20:10
Computers are pretty fast nowadays but not fast enough to start a language server after each keypress, communicate with it, and then quit

**Comment by aliusmiles** [comment] 2020-02-14 17:56
@juliosueiras  CPU spikes in vscode seems to be inconsistent and just starting when typing really fast. I'll try to gather some more data on when exactly it happens, but in the meantime is there any way to increase LSP logs verbosity?

**Comment by aliusmiles** [comment] 2020-02-14 18:22
Just spend some time testing, managed to achieve only small spike, LSP is still working. But no huge spikes, when VSCode even slows to display typed in characters, up to almost freeze, and LSP crashes afterwards. Will definitely collect logs next time it happens.


My usual workflow is: multiple VSCode windows, some with 0.12 and lsp, some with 0.11, some projects are quite complicated, with multiple resources and multiple locals blocks.

Just a thought: wouldn't continuously running (till window opened?) lang server be better then constant starts/stops? No idea how other lang servers are implemented in that regards, briefly worked only with puppet one, and it did not seem to have cpu spikes issue.

**Comment by juliosueiras** [comment] 2020-02-17 06:03
@aliusmiles can you try v0.0.10? did some fixes regarding this

**Comment by aliusmiles** [comment] 2020-02-17 19:18
@juliosueiras I didn't have time for extensive testing today, but short tests shows 0.0.10 is indeed much better, thanks a lot!

 I should be doing some 0.12 updates this week, will update/create new issues if I encounter any problems. In that regards would you mind suggesting how to enable lsp verbose logging in vscode? configure args in .vscode/setting.json?

**Comment by juliosueiras** [comment] 2020-04-21 16:37
closing this since the recursive bug has been fixed

**Closed by juliosueiras** 2020-04-21 16:37 UTC
