### ISSUE TITLE
tfvar's files not accepting variable definitions

### ISSUE THREAD

**Issue by djsly** [juliosueiras/terraform-lsp#39] opened 2019-11-05 02:42 UTC
```test.terraform.tfvars
# fake values for tests
name          = "NAME"
namespace     = "NAMESPACE"
chart_name    = "reactiveops-stable/rbac-manager"
chart_version = "1.1.2"
```

error
```
{
	"resource": "test.terraform.tfvars",
	"owner": "_generated_diagnostic_collection_name_#3",
	"severity": 8,
	"message": "An argument named \"name\" is not expected here.",
	"source": "Terraform",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 5
}
{
	"resource": "test.terraform.tfvars",
	"owner": "_generated_diagnostic_collection_name_#3",
	"severity": 8,
	"message": "An argument named \"namespace\" is not expected here.",
	"source": "Terraform",
	"startLineNumber": 3,
	"startColumn": 1,
	"endLineNumber": 3,
	"endColumn": 10
}
```

**Comment by Fabian1976** [comment] 2020-01-22 07:34
Any update/progress on this issue? Having the same problem.

**Comment by MostHated** [comment] 2020-01-25 04:54
I am having this issue as well.

**Comment by unkn0wn-root** [comment] 2020-01-28 09:10
Any progress? Still having the same issue...

**Comment by adresan** [comment] 2020-01-31 09:01
This issue still exists. And i want to add that the same issue occur on **.hcl** files also. Its a general problem and all variables on **.tfvars** and **.hcl** files are marked as '_An argument named '...' is not expected here_'.

**Comment by apoorva-ovgu** [comment] 2020-01-31 17:42
Is there an update here? I am facing the same issue.

**Comment by bogdanfe** [comment] 2020-02-12 18:53
I'm experiencing the same issue.

**Comment by Rabattkarte** [comment] 2020-02-13 13:04
+1

**Comment by losojos27** [comment] 2020-02-13 15:23
+1

**Comment by peter-dolkens** [comment] 2020-02-13 17:27
This is not a bug.

Behavior changed to require you to explicitly declare all variables found in tfvars

This means you need to declare all variables as described here: https://www.terraform.io/docs/configuration/variables.html

**Comment by Rabattkarte** [comment] 2020-02-13 17:36
@peter-dolkens I declare every single variable in my *.tf-files and still have this bug in my *.tfvars-files. I'm happy to provide any needed information on used versions etc.

**Comment by MostHated** [comment] 2020-02-13 17:37
Same, I have explicitly declared types as per the document linked as well as filling out all of the additional parameters and still get the error in tfvars file.

**Comment by adresan** [comment] 2020-02-13 18:26
@peter-dolkens Its definitely a bug and of course you have to provide the variable declarions, else it would be not possible to pass .tfvars and .hcl files through the CLI to you root module what is a very common usecase when you have different stages with different backends at the same terraform code base. But even when they belongs to the root module, it does not work with .tfvars and .hcl files. 

By the way, with the old language server this error does not occur.

**Comment by Sk8rMarc** [comment] 2020-02-28 19:22
> This is not a bug.
> 
> Behavior changed to require you to explicitly declare all variables found in tfvars
> 
> This means you need to declare all variables as described here: https://www.terraform.io/docs/configuration/variables.html

I'm having the same issue.  I'm using version v0.0.10.  We use Terraform with AWS.

Typically, our terraform stacks are Makefile driven.  Such Makefile's set up our automation environment, pulling target configuration parameters we store in AWS config for a given AWS profile.  Application Terraform stacks typically have a **vars** directory containing a plethora of **tfvars** files for use with different stack configurations for different target environments.  These Makefiles generate the tfvars filename from AWS configuration parameters, referenced down in this **vars** directory.

I'm getting the "An argument named [...] is not expected here. Terraform" errors now  as well.

**Comment by CsBigDataHub** [comment] 2020-03-18 16:09
looks like there is a issue opened with [vscode-terraform](https://github.com/mauve/vscode-terraform/issues/218) as well.

**Comment by juliosueiras** [comment] 2020-04-21 16:38
the issue should be resolved in the latest version, since tfvars now uses a different error check then normal .tf

**Closed by juliosueiras** 2020-04-21 16:38 UTC
